package leetcode;

public class FindDiff {

	/*
	 * String t is generated by random shuffling string s and then add one more
	 * letter at a random position.
	 */
	public char findTheDifference(String s, String t) {
		if (s == null || t == null) {
			return 'a';
		}
		int[] chs = new int[26];
		for (int i = 0; i < 26; i++) {
			chs[i] = 0;
		}
		for (int i = 0; i < s.length(); i++) {
			chs[s.charAt(i) - 'a'] += 1;
		}
		for (int i = 0; i < t.length(); i++) {
			chs[t.charAt(i) - 'a'] -= 1;
		}
		
		for (int i = 0; i < 26; i++) {
			if (chs[i] != 0) {
				return (char) ('a' + i);
			}
		}
		return 'a';
	}
	
	// bit ^
	public char findTheDifference2(String s, String t) {
		char c = 0;
		for (int i = 0; i < s.length(); i++) {
			c ^= s.charAt(i);
		}
		
		for (int i = 0; i < t.length(); i++) {
			c ^= t.charAt(i);
		}
		return c;
	}
}
